### ISSUE TITLE
Adding a dust emission component when fitting SED model to photometric data causes jupyter kernel to freeze and hang

### ISSUE THREAD

**Issue by shruti-ramaiya** [ACCarnall/bagpipes#75]
Hi Adam,

I'm currently using BAGPIPES to fit an SED to some photometric data. I've followed the instructions in the Guthub example tutorial notebooks to get my flux and flux errors in the way BAGPIPES expects. I then fit an SED to the photometric data using the following combination of model parameters.

`exp = {}                                  # Tau-model star-formation history component
exp["age"] = (0.1, 40.)                   # Vary age between 100 Myr and 40 Gyr. In practice 
                                          # the code automatically limits this to the age of
                                          # the Universe at the observed redshift.

exp["tau"] = (0.1, 40.)                   # Vary tau between 100 Myr and 40 Gyr
exp["massformed"] = (0.1, 18.)            # vary log_10(M*/M_solar) between .1 and 18
exp["metallicity"] = (0., 15)             # vary Z between 0 and 15 Z_oldsolar

dust = {}                                 # Dust component
dust["type"] = "Calzetti"                 # Define the shape of the attenuation curve
dust["Av"] = (0., 6.)                     # Vary Av between 0 and 2 magnitudes

fit_instructions = {}                     # The fit instructions dictionary
fit_instructions["redshift"] = cat[cat['CID'] == int(galaxy.ID)]['REDSHIFT_SPEC'].values[0] # fixing redshift to spec z
fit_instructions["exponential"] = exp   
fit_instructions["dust"] = dust

`

This works fine (although it gives a MULTINEST "mode is converging to prior" warning even though the contours are fully constrained) and gives a model SED that looks like such,

<img width="984" alt="Screenshot 2024-05-24 at 13 44 15" src="https://github.com/ACCarnall/bagpipes/assets/95286997/6870bce1-08a2-45e2-8556-fe67cc8281b5">

Now, of course this is not the 'best' model as the photometric data clearly shows re-emission at far infrared wavelengths and this model doesnt fit for that. Though that is expected as there is no dust emission component stated in the above model parameters.

When I add a dust emission component to the model using the following lines,

`#dust emission model
dust["qpah"] = (0.1,5.)                    # PAH mass fraction
dust["umin"] = (0.1,25.)                   # Lower limit of starlight intensity distribution
dust["gamma"] = (0.0005 ,1)                     # Fraction of stars at umin
`

The code doesnt stop running and repeatedly produces the following output until it takes up so much memory from the output lines below that my jupyter notebook freezes and dies,

`Bagpipes: fitting object 1435094

 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    8
 *****************************************************
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x297b0f100>
Traceback (most recent call last):
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11/site-packages/bagpipes/fitting/fitted_model.py", line 146, in lnlike
    self.model_galaxy.update(self.model_components)
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11/site-packages/bagpipes/models/model_galaxy.py", line 320, in update
    self._calculate_full_spectrum(model_components)
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11/site-packages/bagpipes/models/model_galaxy.py", line 433, in _calculate_full_spectrum
    spectrum += dust_flux*self.dust_emission.spectrum(qpah, umin,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11[/](https://file+.vscode-resource.vscode-cdn.net/)site-packages/bagpipes/models/dust_emission_model.py", line 30, in spectrum
    / (config.qpah_vals[qpah_ind]
       ~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: index 11 is out of bounds for axis 0 with size 11
Exception ignored on calling ctypes callback function: <function run.<locals>.loglike at 0x297b0f100>
Traceback (most recent call last):
  File "/Users/shrutiramaiya/anaconda3/envs/bpipes/lib/python3.11/site-packages/pymultinest/run.py", line 228, in loglike
    return LogLikelihood(cube, ndim, nparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

I'm not sure what the problem is and how else I can fix this, as all I did was add three lines. If you have any insights I would be most grateful!
Thanks,

Shruti

**Comment by ACCarnall** [comment]
Hi there,

Yes, 4.58 is the maximum possible value for this parameter. Dust emission in the far-IR isn't particularly easy to see in plots with f_lambda on the y axis like this, I'd recommend making your own plots with f_nu or energy units on the y axis to be able to see things better. Aside from this, the strength of the dust emission is directly related to the amount of energy removed from the UV-optical by the dust attenuation, an assumption usually called energy balance. This can sometimes be inappropriate for some galaxies, though it's usually a reasonable approximation on average.

Cheers,
Adam

**Comment by shruti-ramaiya** [comment]
Hi Adam,

Thanks for getting back to me and for the suggestion - I'll go ahead and try that

Cheers

**Comment by ErikOsinga** [comment]
Hi, 

Is there any reason why qpah cannot be larger than 4.58?

**Comment by shruti-ramaiya** [comment]
I think because bagpipes uses Draine and Li dust emission models and each has a qpah value assigned to it - link to paper: https://iopscience.iop.org/article/10.1086/518306/pdf (I haven't read this yet so might be wrong here)

**Comment by ACCarnall** [comment]
Yes this is the reason.
